version: "3"

services:
  cloudflared:
    #image: visibilityspots/cloudflared
    image: cloudflare/cloudflared
    container_name: cloudflared
      #command: proxy-dns
    ports:
      - "5054:5054/tcp"
      - "5054:5054/udp"
    command: "proxy-dns --address :: --port 5054 --upstream https://1.1.1.1/dns-query --upstream https://1.0.0.1/dns-query --upstream https://[2606:4700:4700::1111]/dns-query --upstream https://[2606:4700:4700::1001]/dns-query"
    environment:
      #TUNNEL_DNS_UPSTREAM: https://1.1.1.1/dns-query,https://1.0.0.1/dns-query
      TUNNEL_DNS_PORT: 5054
      TUNNEL_DNS_ADDRESS: 0.0.0.0
      PROXY_DNS_ADDRESS: ::1
      #TZ: Asia/Jakarta
      #PORT: 5054
      #ADDRESS: 0.0.0.0
      #UPSTREAM1: https://1.1.1.1/dns-query
      #UPSTREAM2: https://1.0.0.1/dns-query
    restart: always
    networks:
      cloudflare_net:
        ipv4_address: 10.0.0.2

          #  googled:
          #    image: visibilityspots/cloudflared
          #    container_name: googled
          #    ports:
          #      - '5055:5055/tcp'
          #      - '5055:5055/udp'
          #    environment:
          #      TZ: Asia/Jakarta
          #      PORT: 5055
          #      UPSTREAM1: https://8.8.8.8/dns-query
          #      UPSTREAM2: https://8.4.4.8/dns-query
          #    restart: always
          #    networks:
          #      cloudflare_net:
          #        ipv4_address: 10.0.0.5

  quad9:
    image: cloudflare/cloudflared
    container_name: quad9
    command: proxy-dns
    ports:
      - '5056:5056/tcp'
      - '5056:5056/udp'
    environment:
      #TZ: Asia/Jakartaa
      TUNNEL_DNS_ADDRESS: 0.0.0.0
      TUNNEL_DNS_PORT: 5056
      TUNNEL_DNS_UPSTREAM: https://9.9.9.9/dns-query,https://149.112.112.112/dns-query
        #UPSTREAM2: 
    restart: always
    networks:
      cloudflare_net:
        ipv4_address: 10.0.0.6

  next:
    image: cloudflare/cloudflared
    container_name: next
    command: proxy-dns
    ports:
      - '5057:5057/tcp'
      - '5057:5057/udp'
    environment:
      #TZ: Asia/Jakarta
      TUNNEL_DNS_ADDRESS: 0.0.0.0
      TUNNEL_DNS_PORT: 5057
      TUNNEL_DNS_UPSTREAM: https://dns.nextdns.io/2cbfa8,https://dns.nextdns.io/2cbfa8
        #UPSTREAM2: 
    restart: always
    networks:
      cloudflare_net:
        ipv4_address: 10.0.0.7

networks:
  cloudflare_net:
    #external: true
    name: cloudflare_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/28
